cache: &default-cache
    key: '${CI_COMMIT_REF_SLUG}'
    paths:
        - generated/

stages:
    - retrieve
    - deploy

# ---

deploy:versions:
    before_script:
        - 'apk add --no-cache --no-progress ca-certificates git'
        - 'git config --global user.email "${GIT_USER_EMAIL}"'
        - 'git config --global user.name "${GIT_USER_NAME}"'
        - 'git remote set-url origin "https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"'
    cache:
        <<: *default-cache
        policy: pull
    image:
        entrypoint: ['']
        name: alpine:latest
    only:
        - master
    script:
        - 'rm -f -r $(ls | grep -v generated)'
        - 'mv generated/* ./'
        - 'rm -f -r .gitignore .gitlab-ci.yml .php_cs.dist generated'
        - 'git checkout --orphan generated'
        - 'git add -A'
        - 'git commit -m "$(date --utc ''+%Y-%m-%d %H:%M'')"'
        - 'git push origin generated --force'
    stage: deploy

retrieve:versions:
    before_script:
        - 'composer config -g github-oauth.github.com "${GITHUB_TOKEN}"'
    cache:
        <<: *default-cache
        policy: push
    except:
        - generated
    image:
        entrypoint: ['']
        name: timonier/php:cli
    script:
        - 'bin/retrieve-versions'
    stage: retrieve
